version: "3"
services:

  todo_backend:
    image: todo_backend
    ports:
      - 80:8000
    volumes:
      - .:/opt/app
    command: python3 start.py
    env_file:
      - .env.config
    build: .
    depends_on:
      - todo_db

  todo_db:
    image: mysql:9.1.0
    ports:
      - 3307:3306
    env_file:
      - .env.config
    volumes:
      - ./dbdata:/var/lib/mysql/